### ISSUE TITLE
v3 Fails to compile with laravel mix

### ISSUE THREAD

**Issue by xaoseric** [almasaeed2010/AdminLTE#1922]
### Issue type:
- [ ] Feature request 
- [ x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 3.0.0 Alpha 2
* Operating System:  Windows
* Browser (Version):  Firefox/Chrome (Latest)

### Description:
The building of AdminLTE 3.0.0 Alpha 2 fails with laravel mix

```
ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed: 
undefined
^
      File to import not found or unreadable: ../../node_modules/bootstrap/scss/functions.
      in C:\xampp\htdocs\Ticketoid\node_modules\admin-lte\build\scss\AdminLTE.scss (line 9, column 1)
    at runLoaders (C:\xampp\htdocs\Ticketoid\node_modules\webpack\lib\NormalModule.js:195:19)
    at C:\xampp\htdocs\Ticketoid\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\xampp\htdocs\Ticketoid\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\xampp\htdocs\Ticketoid\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (C:\xampp\htdocs\Ticketoid\node_modules\sass-loader\lib\loader.js:55:13)
    at Object.done [as callback] (C:\xampp\htdocs\Ticketoid\node_modules\neo-async\async.js:7974:18)
    at options.error (C:\xampp\htdocs\Ticketoid\node_modules\node-sass\lib\index.js:294:32)
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

**Comment by xaoseric** [comment]
Changing the code to the following seems to have fixed the issue with compiling on laravel:

```
@import "~bootstrap/scss/functions";
@import "bootstrap-variables";
@import "~bootstrap/scss/bootstrap";
```

**Comment by almasaeed2010** [comment]
Hello @xaoseric 

The new adminlte can be loaded into your own scss files by using `AdminLTE-raw`.

Here is my app.scss in a new laravel project:
```scss
@import "~bootstrap/scss/bootstrap";
@import "~admin-lte/build/scss/AdminLTE-raw";
```
You can include any custom variables before `bootstratp`.

Thanks!
