### ISSUE TITLE
animation & wow.js not working

### ISSUE THREAD

**Issue by lhcxhj** [almasaeed2010/AdminLTE#690]
Can any one assist in rectifying this problem? Thanks alot

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

2angular.min.js:2923 

Error: [$compile:ctreq] http://errors.angularjs.org/1.3.7/$compile/ctreq?p0=carousel&p1=slide
    at Error (native)
    at http://umelas.com/js/angular/angular.min.js:24:20
    at L (http://umelas.com/js/angular/angular.min.js:1626:45)
    at v (http://umelas.com/js/angular/angular.min.js:1716:115)
    at http://umelas.com/js/angular/angular.min.js:1884:33
    at http://umelas.com/js/angular/angular.min.js:3244:42
    at l.$eval (http://umelas.com/js/angular/angular.min.js:3639:32)
    at l.$digest (http://umelas.com/js/angular/angular.min.js:3582:56)
    at l.$apply (http://umelas.com/js/angular/angular.min.js:3662:31)
    at l (http://umelas.com/js/angular/angular.min.js:2326:69)

**Comment by almasaeed2010** [comment]
Hello @lhcxhj 
You might wanna refer to wow.js for help since we are not using the script. Thanks and sorry for the inconvenience.

https://github.com/matthieua/WOW
